services:
  - type: web
    name: tecky-compile-server
    runtime: python
    buildCommand: >
      pip install -r requirements.txt &&
      curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=./bin sh &&
      mkdir -p ./arduino_data &&
      ./bin/arduino-cli config init --config-file ./arduino_data/arduino-cli.yaml &&
      ./bin/arduino-cli --config-file ./arduino_data/arduino-cli.yaml config set directories.data ./arduino_data &&
      ./bin/arduino-cli --config-file ./arduino_data/arduino-cli.yaml config set directories.downloads ./arduino_data/staging &&
      ./bin/arduino-cli --config-file ./arduino_data/arduino-cli.yaml config set directories.user ./arduino_data/user &&
      ./bin/arduino-cli --config-file ./arduino_data/arduino-cli.yaml core update-index &&
      ./bin/arduino-cli --config-file ./arduino_data/arduino-cli.yaml core install arduino:avr
    startCommand: python server.py
    plan: free
